Roles:
  - Name: Administrator
    Authority: 10
    Policies:
      - Resource: User
        Index: true
        Create: true
        Read: true
        Update: true
        Delete: true
      - Resource: Role
        Index: true
        Create: true
        Read: true
        Update: true
        Delete: true
